name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: mingc/android-build-box
      volumes:
        - ./:/project
    steps:
      - name: Check for dockerenv file
        run: (cd /project; ./gradlew build)

